<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK10qust\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK10qust/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK10qust.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK10qust\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK10qust\appDevDebugProjectContainer([
    'container.build_hash' => 'K10qust',
    'container.build_id' => '4cc2e4fe',
    'container.build_time' => 1670957993,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK10qust');
